import React, { useState, useEffect } from 'react'
import { 
  ArrowLeft, 
  MapPin, 
  Zap, 
  Clock, 
  DollarSign, 
  Star, 
  Navigation, 
  Map,
  List,
  CreditCard,
  Phone,
  Mail,
  Calendar,
  Battery,
  Route,
  AlertCircle,
  CheckCircle,
  Gauge,
  ChevronRight,
  Users,
  Wifi,
  Car as CarIcon,
  Coffee,
  ShoppingBag,
  Loader2,
  Download,
  Compass,
  MapPinned,
  Fuel,
  Timer,
  TrendingUp,
  Shield,
  Award,
  Target,
  Flag,
  Navigation2
} from 'lucide-react'
import { toast } from 'react-hot-toast'
import TripMap from './TripMap'
import { tripAIService, tripAIUtils } from '../services/tripAIService'

const TripResults = ({ tripPlan, formData, onBack }) => {
  const [viewMode, setViewMode] = useState('roadmap') // 'roadmap' or 'map'
  const [selectedStation, setSelectedStation] = useState(null)
  const [showBookingModal, setShowBookingModal] = useState(false)
  const [isBooking, setIsBooking] = useState(false)

  if (!tripPlan) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">No Trip Data</h2>
          <p className="text-gray-600 mb-4">Unable to load trip planning results.</p>
          <button
            onClick={onBack}
            className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Back to Planning
          </button>
        </div>
      </div>
    )
  }

  // Use utility functions directly from tripAIUtils

  const handleBulkBooking = async (bookingData) => {
    setIsBooking(true)
    try {
      const result = await tripAIService.bulkBookSessions(bookingData)

      if (result.success) {
        toast.success(`Successfully booked ${result.data.successfulBookings} charging sessions!`)
        setShowBookingModal(false)
        // Redirect to bookings page or show confirmation
        if (result.data.failedBookings > 0) {
          toast.warning(`${result.data.failedBookings} bookings failed. Check your email for details.`)
        }
      } else {
        toast.error(result.message || 'Failed to book charging sessions')
      }
    } catch (error) {
      console.error('Bulk booking error:', error)
      toast.error(error.message || 'Failed to process booking. Please try again.')
    } finally {
      setIsBooking(false)
    }
  }

  const downloadTripPlan = () => {
    try {
      // Create a comprehensive trip plan text
      const tripText = `
🗺️ EV TRIP PLAN - Generated by DallyTech Trip AI

📍 Route Overview:
${tripPlan.route.from.name} → ${tripPlan.route.to.name}
${tripPlan.route.viaLocations ? tripPlan.route.viaLocations.map((via, i) => `Via ${i+1}: ${via.name}`).join('\n') : ''}

📊 Trip Summary:
• Total Distance: ${tripPlan.totalDistance}km
• Total Time: ${tripAIUtils.formatTime(tripPlan.totalTime)}
• Charging Stops: ${tripPlan.chargingSessions.length}
• Total Cost: ${tripAIUtils.formatCurrency(tripPlan.totalCost)}

🔋 Starting Conditions:
• Initial Battery: ${tripPlan.initialBatteryPercent}%
• Vehicle Range: ${formData.vehicleEfficiency}km (full charge)

${tripPlan.chargingSessions.length > 0 ? `
⚡ Charging Plan:
${tripPlan.chargingSessions.map((session, index) => {
  const isInitialCharge = session.isInitialCharge || session.sessionNumber === 0;
  const locationInfo = isInitialCharge 
    ? `${session.distanceFromStart}km from start` 
    : session.station.address?.city || 'Location';
  
  return `
${index + 1}. ${session.station.name}${isInitialCharge ? ' (Initial Charge)' : ''}
   📍 ${locationInfo}
   ⏰ Arrival: ${new Date(session.estimatedArrival).toLocaleString()}
   🔋 Battery: ${session.batteryOnArrival}% → ${session.batteryAfterCharging}%
   ⚡ Energy: +${session.energyRequired}kWh
   💰 Cost: ${tripAIUtils.formatCurrency(session.cost)}
   ⏱️ Duration: ${tripAIUtils.formatTime(session.chargingTime)}${isInitialCharge && session.travelTimeToStation ? `
   🚗 Travel time: ${tripAIUtils.formatTime(session.travelTimeToStation)}` : ''}
`;
}).join('')}
` : '🎉 No charging required for this trip!'}

🏁 Destination:
• Final Battery: ${tripPlan.finalBatteryPercentage}%
• Arrival Location: ${tripPlan.route.to.name}

Generated on: ${new Date().toLocaleString()}
Powered by DallyTech Trip AI 🚗⚡
      `.trim()

      // Create and download the file
      const blob = new Blob([tripText], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `trip-plan-${tripPlan.route.from.name.replace(/\s+/g, '-')}-to-${tripPlan.route.to.name.replace(/\s+/g, '-')}.txt`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      
      toast.success('Trip plan downloaded successfully!')
    } catch (error) {
      console.error('Download error:', error)
      toast.error('Failed to download trip plan')
    }
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Mobile-Native Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-40">
        <div className="px-4 py-3">
          {/* Top Row */}
          <div className="flex items-center justify-between mb-3">
            <button
              onClick={onBack}
              className="p-2 -ml-2 text-gray-700 hover:bg-gray-100 rounded-full transition-colors active:bg-gray-200"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <h1 className="text-lg font-semibold text-gray-900">Trip Plan</h1>
            <div className="w-9"></div> {/* Spacer for centering */}
          </div>
          
          {/* Route Info */}
          <div className="text-center mb-3">
            <p className="text-sm text-gray-600 truncate">
              {tripPlan.route.from.name}
              {tripPlan.route.viaLocations && tripPlan.route.viaLocations.length > 0 && 
                tripPlan.route.viaLocations.map((via, index) => ` → ${via.name}`).join('')
              }
              → {tripPlan.route.to.name}
            </p>
          </div>
          
          {/* View Toggle - Mobile Optimized */}
          <div className="flex bg-gray-100 rounded-lg p-1">
            <button
              onClick={() => setViewMode('roadmap')}
              className={`flex-1 flex items-center justify-center space-x-2 py-2 px-3 rounded-md font-medium transition-colors ${
                viewMode === 'roadmap'
                  ? 'bg-white text-blue-600 shadow-sm'
                  : 'text-gray-600'
              }`}
            >
              <List className="w-4 h-4" />
              <span className="text-sm">Route</span>
            </button>
            <button
              onClick={() => setViewMode('map')}
              className={`flex-1 flex items-center justify-center space-x-2 py-2 px-3 rounded-md font-medium transition-colors ${
                viewMode === 'map'
                  ? 'bg-white text-blue-600 shadow-sm'
                  : 'text-gray-600'
              }`}
            >
              <Map className="w-4 h-4" />
              <span className="text-sm">Map</span>
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Trip Details */}
          <div className="lg:col-span-2">
            {viewMode === 'roadmap' ? (
              <RoadmapView 
                tripPlan={tripPlan} 
                formData={formData}
                onStationSelect={setSelectedStation}
              />
            ) : (
              <MapView 
                tripPlan={tripPlan}
                onStationSelect={setSelectedStation}
              />
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Quick Actions */}
            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Actions</h3>
              <div className="space-y-3">
                {tripPlan.chargingSessions && tripPlan.chargingSessions.length > 0 && (
                  <button
                    onClick={() => setShowBookingModal(true)}
                    className="w-full py-3 px-4 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
                  >
                    <CreditCard className="w-4 h-4 inline mr-2" />
                    Book All Stations
                  </button>
                )}
                <button
                  onClick={() => {
                    // Share functionality
                    if (navigator.share) {
                      navigator.share({
                        title: 'My EV Trip Plan',
                        text: `Check out my AI-generated trip plan from ${tripPlan.route.from.name} to ${tripPlan.route.to.name}`,
                        url: window.location.href
                      })
                    } else {
                      navigator.clipboard.writeText(window.location.href)
                      toast.success('Trip link copied to clipboard!')
                    }
                  }}
                  className="w-full py-3 px-4 bg-white border border-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-50 transition-colors"
                >
                  Share Trip Plan
                </button>
                <button
                  onClick={downloadTripPlan}
                  className="w-full py-3 px-4 bg-green-600 text-white font-medium rounded-lg hover:bg-green-700 transition-colors"
                >
                  <Download className="w-4 h-4 inline mr-2" />
                  Download Plan
                </button>
              </div>
            </div>

            {/* Cost Breakdown */}
            <div className="bg-white rounded-2xl shadow-xl p-6 border border-gray-100">
              <h3 className="text-lg font-bold text-gray-900 mb-4">Cost Breakdown</h3>
              {tripPlan.chargingSessions && tripPlan.chargingSessions.length > 0 ? (
                <div className="space-y-3">
                  {tripPlan.chargingSessions.map((session, index) => {
                    // Calculate base cost (total cost minus platform fee)
                    const baseCost = session.cost - 10; // ₹10 platform fee per session
                    return (
                      <div key={index} className="flex justify-between items-center py-2 border-b border-gray-100 last:border-b-0">
                        <div className="text-sm">
                          <div className="font-medium text-gray-900">{session.station.name}</div>
                          <div className="text-gray-500">{session.energyRequired}kWh</div>
                        </div>
                        <div className="text-right text-sm">
                          <div className="font-semibold text-gray-900">{tripAIUtils.formatCurrency(session.cost)}</div>
                          <div className="text-gray-500 text-xs">Base: {tripAIUtils.formatCurrency(baseCost)} + ₹10 fee</div>
                        </div>
                      </div>
                    )
                  })}
                  <div className="pt-3 border-t-2 border-gray-200">
                    <div className="space-y-2">
                      <div className="flex justify-between items-center text-sm text-gray-600">
                        <span>Platform Fee ({tripPlan.chargingSessions.length} stations × ₹10)</span>
                        <span>{tripAIUtils.formatCurrency(tripPlan.chargingSessions.length * 10)}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="font-bold text-gray-900">Total</span>
                        <span className="font-bold text-xl text-purple-600">
                          {tripAIUtils.formatCurrency(tripPlan.totalCost)}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="text-center py-6">
                  <Battery className="w-12 h-12 text-green-500 mx-auto mb-3" />
                  <p className="text-gray-600 font-medium mb-1">No Charging Required!</p>
                  <p className="text-sm text-gray-500">Your current battery is sufficient for this trip</p>
                  <div className="mt-3 p-3 bg-green-50 rounded-lg border border-green-200">
                    <div className="flex items-center justify-center text-green-700">
                      <CheckCircle className="w-4 h-4 mr-2" />
                      <span className="font-medium">Total Cost: ₹0</span>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Trip Tips */}
            <div className="bg-gradient-to-br from-blue-50 to-purple-50 rounded-2xl p-6 border border-blue-100">
              <h3 className="text-lg font-bold text-gray-900 mb-4">💡 AI Tips</h3>
              <div className="space-y-3 text-sm">
                <div className="flex items-start space-x-2">
                  <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Your route is optimized for minimal charging time</span>
                </div>
                <div className="flex items-start space-x-2">
                  <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">All selected stations have high availability</span>
                </div>
                <div className="flex items-start space-x-2">
                  <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">Estimated arrival times include traffic patterns</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bulk Booking Modal */}
      {showBookingModal && (
        <BulkBookingModal
          tripPlan={tripPlan}
          onClose={() => setShowBookingModal(false)}
          onConfirm={handleBulkBooking}
          isLoading={isBooking}
        />
      )}
    </div>
  )
}

// Professional Modern Roadmap View Component
const RoadmapView = ({ tripPlan, formData, onStationSelect }) => {
  const currentBatteryRange = (formData.vehicleEfficiency * formData.currentBatteryPercent) / 100
  
  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      {/* Clean Professional Header */}
      <div className="bg-gradient-to-r from-gray-50 to-gray-100 px-6 py-4 border-b border-gray-200">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">Route Overview</h2>
            <p className="text-sm text-gray-600 mt-1">
              {tripPlan.route.from.name} → {tripPlan.route.to.name}
            </p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-bold text-blue-600">{tripPlan.totalDistance}km</div>
            <div className="text-sm text-gray-500">Total Distance</div>
          </div>
        </div>
      </div>

      {/* Clean Statistics Grid */}
      <div className="p-4 bg-gray-50 border-b border-gray-200">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          <div className="bg-white rounded-lg p-3 text-center border border-gray-200">
            <Timer className="w-5 h-5 text-blue-600 mx-auto mb-1" />
            <div className="font-semibold text-gray-900">{tripAIUtils.formatTime(tripPlan.totalTime)}</div>
            <div className="text-xs text-gray-500">Total Time</div>
          </div>
          <div className="bg-white rounded-lg p-3 text-center border border-gray-200">
            <Zap className="w-5 h-5 text-purple-600 mx-auto mb-1" />
            <div className="font-semibold text-gray-900">{tripPlan.chargingSessions.length}</div>
            <div className="text-xs text-gray-500">Charging Stops</div>
          </div>
          <div className="bg-white rounded-lg p-3 text-center border border-gray-200">
            <DollarSign className="w-5 h-5 text-green-600 mx-auto mb-1" />
            <div className="font-semibold text-gray-900">{tripAIUtils.formatCurrency(tripPlan.totalCost)}</div>
            <div className="text-xs text-gray-500">Total Cost</div>
          </div>
          <div className="bg-white rounded-lg p-3 text-center border border-gray-200">
            <Battery className="w-5 h-5 text-emerald-600 mx-auto mb-1" />
            <div className="font-semibold text-gray-900">{tripPlan.finalBatteryPercentage}%</div>
            <div className="text-xs text-gray-500">Final Battery</div>
          </div>
        </div>
      </div>

      {/* Professional Route Timeline */}
      <div className="p-6">
        <div className="relative max-w-4xl mx-auto">
          {/* Clean Route Line */}
          <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-gradient-to-b from-blue-200 via-purple-200 to-green-200"></div>

          {/* Starting Point - Clean Design */}
          <div className="relative mb-8">
            <div className="flex items-start">
              <div className="relative z-10 w-12 h-12 bg-green-500 rounded-full flex items-center justify-center shadow-lg">
                <Flag className="w-6 h-6 text-white" />
              </div>
              <div className="ml-6 flex-1">
                <div className="bg-white rounded-lg border border-gray-200 p-4 shadow-sm">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                    <div className="mb-3 sm:mb-0">
                      <div className="flex items-center gap-2 mb-1">
                        <MapPin className="w-4 h-4 text-green-600" />
                        <h3 className="text-lg font-semibold text-gray-900">
                          {tripPlan.route.from.name}
                        </h3>
                      </div>
                      <p className="text-sm text-gray-600">Starting point</p>
                      <p className="text-xs text-gray-500 mt-1">
                        {tripPlan.route.from.fullAddress}
                      </p>
                    </div>
                    <div className="text-right">
                      <div className="bg-green-50 rounded-lg p-3">
                        <div className="flex items-center justify-end text-green-700">
                          <Battery className="w-4 h-4 mr-1" />
                          <span className="text-lg font-semibold">{formData.currentBatteryPercent}%</span>
                        </div>
                        <div className="text-xs text-green-600">
                          ~{Math.round(currentBatteryRange)}km range
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Via Points - Clean Professional Design */}
          {tripPlan.route.viaLocations && tripPlan.route.viaLocations.map((viaLocation, index) => (
            <div key={`via-${index}`} className="relative mb-8">
              <div className="flex items-start">
                <div className="relative z-10 w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center shadow-lg">
                  <span className="text-white font-semibold text-sm">{index + 1}</span>
                </div>
                <div className="ml-6 flex-1">
                  <div className="bg-white rounded-lg border border-gray-200 p-4 shadow-sm">
                    <div className="flex items-center gap-2 mb-1">
                      <MapPin className="w-4 h-4 text-blue-600" />
                      <h3 className="text-lg font-semibold text-gray-900">
                        {viaLocation.name}
                      </h3>
                    </div>
                    <p className="text-sm text-gray-600">Via point #{index + 1}</p>
                    <p className="text-xs text-gray-500 mt-1">
                      {viaLocation.fullAddress}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          ))}

          {/* Charging Stations - Clean Professional Design */}
          {tripPlan.chargingSessions.map((session, index) => {
            const isInitialCharge = session.isInitialCharge || session.sessionNumber === 0;
            const isPremium = session.station.dockitRecommended;
            
            return (
              <div key={index} className="relative mb-8">
                <div className="flex items-start">
                  <div 
                    className={`relative z-10 w-12 h-12 rounded-full flex items-center justify-center shadow-lg cursor-pointer hover:shadow-xl transition-shadow ${
                      isInitialCharge 
                        ? 'bg-orange-500' 
                        : isPremium
                        ? 'bg-purple-600'
                        : 'bg-blue-600'
                    }`}
                    onClick={() => onStationSelect(session.station)}
                  >
                    <Zap className="w-6 h-6 text-white" />
                    {isPremium && (
                      <div className="absolute -top-1 -right-1 w-5 h-5 bg-yellow-400 rounded-full flex items-center justify-center">
                        <Star className="w-3 h-3 text-yellow-800" />
                      </div>
                    )}
                  </div>
                  
                  <div className="ml-6 flex-1">
                    <div 
                      className={`bg-white rounded-lg border p-4 shadow-sm cursor-pointer hover:shadow-md transition-shadow ${
                        isPremium ? 'border-purple-200' : 'border-gray-200'
                      }`}
                      onClick={() => onStationSelect(session.station)}
                    >
                      {/* Station Header */}
                      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-4">
                        <div className="mb-3 sm:mb-0 flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <h3 className="text-lg font-semibold text-gray-900">
                              {session.station.name}
                            </h3>
                            {isPremium && (
                              <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                                <Star className="w-3 h-3 mr-1" />
                                Premium
                              </span>
                            )}
                            {isInitialCharge && (
                              <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-orange-100 text-orange-800">
                                Initial Charge
                              </span>
                            )}
                          </div>
                          <div className="flex items-center gap-4 text-sm text-gray-600">
                            <div className="flex items-center gap-1">
                              <MapPin className="w-4 h-4" />
                              <span>
                                {isInitialCharge 
                                  ? `${session.distanceFromStart}km from start` 
                                  : session.station.address?.city}
                              </span>
                            </div>
                            {session.station.rating && (
                              <div className="flex items-center gap-1">
                                <Star className="w-4 h-4 text-yellow-500 fill-current" />
                                <span className="font-medium">{session.station.rating.average?.toFixed(1)}</span>
                                <span className="text-gray-500">({session.station.rating.count})</span>
                              </div>
                            )}
                          </div>
                        </div>
                        
                        <div className="text-right">
                          <div className="bg-gray-50 rounded-lg p-3">
                            <div className="flex items-center justify-end text-gray-900 mb-1">
                              <Clock className="w-4 h-4 mr-1" />
                              <span className="font-semibold">{tripAIUtils.formatTime(session.chargingTime)}</span>
                            </div>
                            <div className="text-lg font-semibold text-green-600">
                              {tripAIUtils.formatCurrency(session.cost)}
                            </div>
                          </div>
                        </div>
                      </div>

                      {/* Session Details Grid */}
                      <div className={`grid gap-3 mb-4 ${isInitialCharge && session.travelTimeToStation ? 'grid-cols-2 sm:grid-cols-5' : 'grid-cols-2 sm:grid-cols-4'}`}>
                        <div className="bg-blue-50 rounded-lg p-3 text-center">
                          <div className="text-xs text-blue-700 mb-1">Arrival</div>
                          <div className="font-semibold text-blue-900 text-sm">
                            {new Date(session.estimatedArrival).toLocaleTimeString('en-US', { 
                              hour: '2-digit', 
                              minute: '2-digit' 
                            })}
                          </div>
                        </div>
                        
                        <div className="bg-orange-50 rounded-lg p-3 text-center">
                          <div className="text-xs text-orange-700 mb-1">Battery</div>
                          <div className="font-semibold text-orange-900 text-sm">
                            {session.batteryOnArrival}% → {session.batteryAfterCharging}%
                          </div>
                        </div>
                        
                        <div className="bg-green-50 rounded-lg p-3 text-center">
                          <div className="text-xs text-green-700 mb-1">Energy</div>
                          <div className="font-semibold text-green-900 text-sm">
                            +{session.energyRequired}kWh
                          </div>
                        </div>
                        
                        <div className="bg-purple-50 rounded-lg p-3 text-center">
                          <div className="text-xs text-purple-700 mb-1">Duration</div>
                          <div className="font-semibold text-purple-900 text-sm">
                            {tripAIUtils.formatTime(session.chargingTime)}
                          </div>
                        </div>

                        {/* Travel Time for Initial Charging Sessions */}
                        {isInitialCharge && session.travelTimeToStation && (
                          <div className="bg-indigo-50 rounded-lg p-3 text-center">
                            <div className="text-xs text-indigo-700 mb-1">Travel Time</div>
                            <div className="font-semibold text-indigo-900 text-sm">
                              {tripAIUtils.formatTime(session.travelTimeToStation)}
                            </div>
                          </div>
                        )}
                      </div>

                      {/* Station Amenities */}
                      {session.station.amenities && session.station.amenities.length > 0 && (
                        <div className="pt-3 border-t border-gray-200">
                          <div className="flex items-center gap-2 mb-2">
                            <Coffee className="w-4 h-4 text-gray-600" />
                            <span className="text-sm font-medium text-gray-700">Amenities</span>
                          </div>
                          <div className="flex flex-wrap gap-2">
                            {session.station.amenities.slice(0, 4).map((amenity, i) => (
                              <span key={i} className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-700">
                                {getAmenityIcon(amenity)}
                                <span className="ml-1">{formatAmenity(amenity)}</span>
                              </span>
                            ))}
                            {session.station.amenities.length > 4 && (
                              <span className="text-xs text-gray-500">+{session.station.amenities.length - 4} more</span>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}

          {/* Destination - Clean Final Point */}
          <div className="relative">
            <div className="flex items-start">
              <div className="relative z-10 w-12 h-12 bg-red-500 rounded-full flex items-center justify-center shadow-lg">
                <Target className="w-6 h-6 text-white" />
              </div>
              <div className="ml-6 flex-1">
                <div className="bg-white rounded-lg border border-gray-200 p-4 shadow-sm">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                    <div className="mb-3 sm:mb-0">
                      <div className="flex items-center gap-2 mb-1">
                        <MapPin className="w-4 h-4 text-red-600" />
                        <h3 className="text-lg font-semibold text-gray-900">
                          {tripPlan.route.to.name}
                        </h3>
                      </div>
                      <p className="text-sm text-gray-600">Destination</p>
                      <p className="text-xs text-gray-500 mt-1">
                        {tripPlan.route.to.fullAddress}
                      </p>
                    </div>
                    <div className="text-right">
                      <div className="bg-red-50 rounded-lg p-3">
                        <div className="flex items-center justify-end text-red-700">
                          <Battery className="w-4 h-4 mr-1" />
                          <span className="text-lg font-semibold">{tripPlan.finalBatteryPercentage}%</span>
                        </div>
                        <div className="text-xs text-red-600">
                          Final battery
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// Map View Component
const MapView = ({ tripPlan, onStationSelect }) => {
  return (
    <div className="bg-white rounded-lg border">
  
      <div className="p-6 border-b border-gray-100">
        <h2 className="text-xl font-bold text-gray-900">Route Map</h2>
        <p className="text-gray-600">Interactive map showing your route and charging stations</p>
      </div>
      
      <div className="h-96 rounded-b-lg overflow-hidden relative">
        <div className="absolute inset-0">
          <TripMap 
            tripPlan={tripPlan}
            onStationSelect={onStationSelect}
          />
        </div>
      </div>
    </div>
  )
}

// Bulk Booking Modal
const BulkBookingModal = ({ tripPlan, onClose, onConfirm, isLoading }) => {
  const [customizedSessions, setCustomizedSessions] = useState([])
  const [slotChecking, setSlotChecking] = useState({})
  const [slotErrors, setSlotErrors] = useState({})
  const [isCheckingAll, setIsCheckingAll] = useState(false)

  // Initialize customized sessions on modal open
  useEffect(() => {
    if (tripPlan?.chargingSessions) {
      setCustomizedSessions(tripPlan.chargingSessions.map(session => ({
        ...session,
        customStartTime: session.estimatedArrival,
        customDuration: session.chargingTime, // This should be the AI-suggested duration
        isCustomized: false
      })))
    }
  }, [tripPlan])

  // Helper function to format datetime for input
  const formatDateTimeForInput = (dateString) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    
    // Format to YYYY-MM-DDTHH:MM for datetime-local input
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    const hours = String(date.getHours()).padStart(2, '0')
    const minutes = String(date.getMinutes()).padStart(2, '0')
    
    return `${year}-${month}-${day}T${hours}:${minutes}`
  }

  // Calculate total cost with customizations (including platform fees)
  const totalCost = customizedSessions.reduce((sum, session) => {
    // Each session cost already includes platform fee from backend
    return sum + session.cost
  }, 0)

  // Check slot availability for a specific session
  const checkSlotAvailability = async (sessionIndex, startTime, duration) => {
    const session = customizedSessions[sessionIndex]
    if (!session) return

    setSlotChecking(prev => ({ ...prev, [sessionIndex]: true }))
    setSlotErrors(prev => ({ ...prev, [sessionIndex]: null }))

    try {
      const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
      const response = await fetch(`${API_BASE_URL}/bookings/check-slot-availability`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({
          stationId: session.station._id,
          portId: session.recommendedPort?._id,
          startTime: new Date(startTime).toISOString(),
          duration: duration
        })
      })

      const result = await response.json()

      if (!result.success) {
        setSlotErrors(prev => ({ 
          ...prev, 
          [sessionIndex]: result.message || 'Slot not available at this time' 
        }))
        return false
      }

      setSlotErrors(prev => ({ ...prev, [sessionIndex]: null }))
      return true
    } catch (error) {
      console.error('Slot availability check error:', error)
      setSlotErrors(prev => ({ 
        ...prev, 
        [sessionIndex]: 'Failed to check slot availability' 
      }))
      return false
    } finally {
      setSlotChecking(prev => ({ ...prev, [sessionIndex]: false }))
    }
  }

  // Handle time slot change
  const handleTimeSlotChange = async (sessionIndex, field, value) => {
    const updatedSessions = [...customizedSessions]
    const session = updatedSessions[sessionIndex]

    if (field === 'startTime') {
      // Convert datetime-local input to ISO string
      const date = new Date(value)
      session.customStartTime = date.toISOString()
      session.isCustomized = true
    } else if (field === 'duration') {
      session.customDuration = parseInt(value)
      session.isCustomized = true
    }

    setCustomizedSessions(updatedSessions)

    // Check availability after a short delay
    setTimeout(() => {
      checkSlotAvailability(sessionIndex, session.customStartTime, session.customDuration)
    }, 500)
  }

  // Reset to AI suggested time
  const resetToAISuggested = (sessionIndex) => {
    const originalSession = tripPlan.chargingSessions[sessionIndex]
    const updatedSessions = [...customizedSessions]
    
    updatedSessions[sessionIndex] = {
      ...updatedSessions[sessionIndex],
      customStartTime: originalSession.estimatedArrival,
      customDuration: originalSession.chargingTime,
      isCustomized: false
    }

    setCustomizedSessions(updatedSessions)
    setSlotErrors(prev => ({ ...prev, [sessionIndex]: null }))
    
    // Clear any checking state
    setSlotChecking(prev => ({ ...prev, [sessionIndex]: false }))
  }

  // Check all slots availability
  const checkAllSlots = async () => {
    setIsCheckingAll(true)
    const results = await Promise.all(
      customizedSessions.map((session, index) => 
        checkSlotAvailability(index, session.customStartTime, session.customDuration)
      )
    )
    setIsCheckingAll(false)
    return results.every(result => result === true)
  }

  // Handle booking confirmation
  const handleConfirmBooking = async () => {
    // Check all slots before proceeding
    const allSlotsAvailable = await checkAllSlots()
    
    if (!allSlotsAvailable) {
      toast.error('Some time slots are not available. Please adjust the times.')
      return
    }

    // Prepare booking data with customized times
    // FIX: Ensure estimatedUnits is passed correctly to maintain pricing consistency
    const bookingData = {
      tripPlanId: tripPlan.id,
      stationBookings: customizedSessions.map(session => {
        const estimatedUnits = session.originalEnergyRequired || session.energyRequired;
        console.log('Booking data for session:', {
          stationName: session.station.name,
          energyRequired: session.energyRequired,
          originalEnergyRequired: session.originalEnergyRequired,
          estimatedUnits: estimatedUnits,
          type: typeof estimatedUnits,
          recommendedPort: session.recommendedPort ? {
            id: session.recommendedPort._id,
            portNumber: session.recommendedPort.portNumber,
            pricePerUnit: session.recommendedPort.pricePerUnit
          } : 'NO RECOMMENDED PORT'
        });
        
        return {
          stationId: session.station._id,
          portId: session.recommendedPort?._id,
          timeSlot: {
            startTime: session.customStartTime,
            duration: session.customDuration
          },
          estimatedUnits: estimatedUnits
        };
      })
    }

    console.log('Final booking data:', bookingData);
    onConfirm(bookingData)
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6 border-b border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">Advanced Trip Booking</h2>
          <p className="text-gray-600">Customize your charging schedule and book all sessions</p>
        </div>

        <div className="p-6">
          {/* Session Customization */}
          <div className="space-y-6 mb-6">
            {customizedSessions.map((session, index) => (
              <div key={index} className="border border-gray-200 rounded-xl p-4">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex-1">
                    <h3 className="font-semibold text-gray-900 flex items-center gap-2">
                      {session.station.name}
                      {session.isCustomized && (
                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                          Customized
                        </span>
                      )}
                    </h3>
                    <p className="text-sm text-gray-600">{session.energyRequired}kWh • {tripAIUtils.formatCurrency(session.cost)}</p>
                  </div>
                  <div className="text-right">
                    <button
                      onClick={() => resetToAISuggested(index)}
                      className="text-sm text-blue-600 hover:text-blue-700 font-medium"
                    >
                      Reset to AI
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Start Time */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Start Time
                    </label>
                                         <input
                       type="datetime-local"
                       value={formatDateTimeForInput(session.customStartTime)}
                       onChange={(e) => handleTimeSlotChange(index, 'startTime', e.target.value)}
                       className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                     />
                  </div>

                  {/* Duration */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Duration (minutes)
                    </label>
                    <select
                      value={session.customDuration}
                      onChange={(e) => handleTimeSlotChange(index, 'duration', e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500"
                    >
                      {/* AI Suggested Duration */}
                      <option value={session.chargingTime}>
                        {session.chargingTime === 60 ? '1 hour' : 
                         session.chargingTime === 90 ? '1.5 hours' : 
                         session.chargingTime === 120 ? '2 hours' : 
                         session.chargingTime === 180 ? '3 hours' : 
                         `${session.chargingTime} minutes`} (AI Suggested)
                      </option>
                      <option value={30}>30 minutes</option>
                      <option value={45}>45 minutes</option>
                      <option value={60}>1 hour</option>
                      <option value={90}>1.5 hours</option>
                      <option value={120}>2 hours</option>
                      <option value={180}>3 hours</option>
                    </select>
                  </div>
                </div>

                {/* AI Suggested Time */}
                <div className="mt-3 p-3 bg-gray-50 rounded-lg">
                  <div className="flex items-center gap-2 text-sm text-gray-600">
                    <Clock className="w-4 h-4" />
                    <span>AI Suggested: {new Date(session.estimatedArrival).toLocaleString()} • {tripAIUtils.formatTime(session.chargingTime)}</span>
                  </div>
                </div>

                {/* Slot Availability Status */}
                <div className="mt-3">
                  {slotChecking[index] && (
                    <div className="flex items-center gap-2 text-sm text-blue-600">
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Checking slot availability...
                    </div>
                  )}
                  {slotErrors[index] && (
                    <div className="flex items-center gap-2 text-sm text-red-600">
                      <AlertCircle className="w-4 h-4" />
                      {slotErrors[index]}
                    </div>
                  )}
                  {!slotChecking[index] && !slotErrors[index] && session.isCustomized && (
                    <div className="flex items-center gap-2 text-sm text-green-600">
                      <CheckCircle className="w-4 h-4" />
                      Slot available
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>

                     {/* Cost Breakdown */}
           <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl p-4 mb-6">
             <div className="flex justify-between items-center mb-2">
               <span className="font-bold text-gray-900">Total Amount</span>
               <span className="text-2xl font-bold text-purple-600">
                 {tripAIUtils.formatCurrency(totalCost)}
               </span>
             </div>
             <div className="text-sm text-gray-600">
               {customizedSessions.length} charging sessions × ₹10 platform fee included
             </div>
             <div className="text-xs text-gray-500 mt-1">
               Each session includes energy cost + ₹10 platform fee
             </div>
           </div>

          {/* Booking Terms */}
          <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-4 mb-6">
            <div className="flex items-start space-x-3">
              <AlertCircle className="w-5 h-5 text-yellow-600 mt-0.5" />
              <div className="text-sm text-yellow-800">
                                 <p className="font-medium mb-1">Beta Mode - Advanced Booking:</p>
                 <ul className="space-y-1 text-xs">
                   <li>• Customize time slots for each charging station</li>
                   <li>• Real-time slot availability checking</li>
                   <li>• ₹10 platform fee per station</li>
                   <li>• All bookings are confirmed instantly</li>
                   <li>• Cancellation possible up to 1 hour before each session</li>
                 </ul>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex space-x-4">
            <button
              onClick={onClose}
              disabled={isLoading || isCheckingAll}
              className="flex-1 py-3 px-4 border border-gray-300 text-gray-700 font-medium rounded-xl hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              onClick={handleConfirmBooking}
              disabled={isLoading || isCheckingAll || Object.keys(slotErrors).some(key => slotErrors[key])}
              className="flex-1 py-3 px-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-xl hover:from-purple-700 hover:to-blue-700 transition-all disabled:opacity-50"
            >
              {isLoading || isCheckingAll ? (
                <div className="flex items-center justify-center">
                  <Loader2 className="w-5 h-5 animate-spin mr-2" />
                  {isCheckingAll ? 'Checking Slots...' : 'Processing...'}
                </div>
              ) : (
                <>
                  <CreditCard className="w-5 h-5 inline mr-2" />
                  Confirm & Pay {tripAIUtils.formatCurrency(totalCost)}
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// Helper functions - using service utilities

const formatAmenity = (amenity) => {
  return amenity.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())
}

const getAmenityIcon = (amenity) => {
  const icons = {
    'wifi': <Wifi className="w-3 h-3" />,
    'cafe': <Coffee className="w-3 h-3" />,
    'restaurant': <Coffee className="w-3 h-3" />,
    'shopping': <ShoppingBag className="w-3 h-3" />,
    'parking': <CarIcon className="w-3 h-3" />,
    'restroom': <Users className="w-3 h-3" />
  }
  return icons[amenity] || <CheckCircle className="w-3 h-3" />
}

export default TripResults 